### ISSUE TITLE
Variables within vocab files not selected relative to representation

### ISSUE THREAD

**Issue by galaxnet** [gorzek/loomwords#19]
When a vocab file for a variable has a different variable included inside that file, that second variable should appear when called relative to the number of lines it appears on. For example, <name_rand> contains numerous lines of names, but also has <name_brit> as 10 lines of the vocab. Yet, <name_brit> is not selected 10x as frequently as any other single line, confounding expectations.

**Comment by gorzek** [comment]
I double-checked the code and realized the vocabs are key-based, so using the same value multiple times in a single vocab won't increase its likelihood of appearing. All unique lines in a vocab file will have an equal chance of being selected, while duplicated lines are automatically deduplicated.

I'd suggest using the `sticky` functionality to make certain terms appear more frequently or perhaps a feature request is in order.

**Comment by gorzek** [comment]
After discussion, closing in favor of #24
