### ISSUE TITLE
Capitalize first word after quotation mark

### ISSUE THREAD

**Issue by galaxnet** [gorzek/loomwords#22]
Please add a default behavior to capitalize the first word after the first quotation mark in a set. Error behavior should default to no change.

**Comment by galaxnet** [comment]
This is a high priority request.

**Comment by gorzek** [comment]
Added to Q3 2022 milestone.

**Comment by gorzek** [comment]
Addressed with 7027dd68222ea3efa0359679842cda75a6c81863
